#!/bin/bash

cat << EOF

Recomendamos executar o R utilizando o Apptainer.
Temos uma imagem pronta que pode ser executada com o comando:

	apptainer exec [38;5;10m--nv[0m /opt/apptainer/ml-verse_latest.sif R

Para instalar pacotes é preciso configurar o .libPaths(). No R, rodar:
    dir.create(Sys.getenv('R_LIBS_USER'), recursive=TRUE)
    .libPaths(Sys.getenv('R_LIBS_USER'))

Mais informações em: http://wiki.ime.usp.br/tutoriais:apptainer

EOF
